name: Build and Pre-release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-trigger:
    runs-on: ubuntu-latest
    name: Check if build should trigger
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
    steps:
    - name: Check commit message or PR title
      id: check
      run: |
        SHOULD_BUILD="false"
        
        # Check commit message for push events
        if [ "${{ github.event_name }}" = "push" ]; then
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MESSAGE"
          if [[ "$COMMIT_MESSAGE" =~ ^BUILD.* ]]; then
            SHOULD_BUILD="true"
            echo "✅ Commit message starts with BUILD"
          else
            echo "❌ Commit message does not start with BUILD"
          fi
        fi
        
        # Check PR title for pull request events
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR title: $PR_TITLE"
          if [[ "$PR_TITLE" =~ ^BUILD.* ]]; then
            SHOULD_BUILD="true"
            echo "✅ PR title starts with BUILD"
          else
            echo "❌ PR title does not start with BUILD"
          fi
        fi
        
        # Always build on manual trigger
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          SHOULD_BUILD="true"
          echo "✅ Manual workflow trigger - building"
        fi
        
        echo "should-build=$SHOULD_BUILD" >> $GITHUB_OUTPUT
        echo "Final decision: should-build=$SHOULD_BUILD"

  create-prerelease:
    runs-on: ubuntu-latest
    needs: check-trigger
    if: needs.check-trigger.outputs.should-build == 'true'
    name: Create Pre-Release
    outputs:
      version: ${{ steps.version.outputs.version }}
      tag: ${{ steps.version.outputs.tag }}
      release-id: ${{ steps.create-release.outputs.id }}
    
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Extract project version and generate incremental version
      id: version
      run: |
        # Extract base project version from ESPHome config
        BASE_VERSION=$(grep -A 2 "project:" serverCollingFanController.yaml | grep "version:" | sed 's/.*version: "\(.*\)".*/\1/')
        echo "Base project version: $BASE_VERSION"
        
        # Get latest release with the same base version to determine next increment
        LATEST_RELEASE=$(gh release list --limit 50 --json tagName,name | jq -r --arg base "v$BASE_VERSION." '.[] | select(.tagName | startswith($base)) | .tagName' | head -1 || echo "")
        
        if [ -z "$LATEST_RELEASE" ]; then
          # No previous releases with this base version, start with .0
          INCREMENTAL_VERSION="${BASE_VERSION}.0"
        else
          # Extract the increment number and add 1
          CURRENT_INCREMENT=$(echo "$LATEST_RELEASE" | sed "s/v${BASE_VERSION}\.//")
          NEXT_INCREMENT=$((CURRENT_INCREMENT + 1))
          INCREMENTAL_VERSION="${BASE_VERSION}.${NEXT_INCREMENT}"
        fi
        
        TAG="v${INCREMENTAL_VERSION}"
        echo "version=$INCREMENTAL_VERSION" >> $GITHUB_OUTPUT
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Base version: $BASE_VERSION"
        echo "Full version: $INCREMENTAL_VERSION"
        echo "Release tag: $TAG"

    - name: Create Pre-Release
      id: create-release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.tag }}
        name: ${{ steps.version.outputs.version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          ## ESPHome Firmware Pre-Release
          
          **Version:** ${{ steps.version.outputs.version }}
          **Build Date:** $(date)
          **Commit:** ${{ github.sha }}

        draft: false
        prerelease: true

  build-firmware:
    name: Build Firmware
    needs: [check-trigger, create-prerelease]
    if: needs.check-trigger.outputs.should-build == 'true'
    uses: DoYouHost/workflows/.github/workflows/build.yml@main
    with:
      files: |
        serverCollingFanController.yaml
      esphome-version: "2025.7.5"
      combined-name: "ServerCoolingFanController"
      release-summary: "Server Cooling Fan Controller v${{ needs.create-prerelease.outputs.version }} - Dual PWM outputs, temperature monitoring, RPM detection, OLED display, and runtime tracking"
      release-url: "https://github.com/DoYouHost/ServerCollingFanController/releases/tag/${{ needs.create-prerelease.outputs.tag }}"
      release-version: "${{ needs.create-prerelease.outputs.version }}"

  upload-to-release:
    name: Upload to Release
    uses: DoYouHost/workflows/.github/workflows/upload-to-gh-release.yml@main
    needs:
      - build-firmware
      - create-prerelease
    with:
      version: ${{ needs.create-prerelease.outputs.version }}

  cleanup-on-failure:
    name: Cleanup Release and Tag on Build Failure
    runs-on: ubuntu-latest
    needs: [create-prerelease, build-firmware]
    if: always() && needs.create-prerelease.result == 'success' && needs.build-firmware.result == 'failure'
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Delete failed release and tag
      run: |
        TAG="${{ needs.create-prerelease.outputs.tag }}"
        echo "Build failed, cleaning up release and tag: $TAG"
        
        # Delete the GitHub release
        gh release delete "$TAG" --yes --cleanup-tag || echo "Release deletion failed or already deleted"
        
        # Delete the Git tag (both locally and remotely)
        git tag -d "$TAG" 2>/dev/null || echo "Local tag not found"
        git push --delete origin "$TAG" 2>/dev/null || echo "Remote tag deletion failed or already deleted"
        
        echo "✅ Cleanup completed for failed build $TAG"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}