name: Promote to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote to production (e.g., 2025.1.5)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  promote-to-production:
    name: Promote to Production
    runs-on: ubuntu-latest
    steps:
      - name: Validate version format
        run: |
          VERSION="${{ inputs.version }}"
          echo "Validating version: $VERSION"
          
          # Check if version follows semantic versioning pattern (YYYY.M.P)
          if [[ "$VERSION" =~ ^[0-9]{4}\.[0-9]+\.[0-9]+$ ]]; then 
            echo "✅ Version $VERSION follows correct pattern (YYYY.M.P)"
          else
            echo "❌ Version $VERSION does not follow expected pattern (YYYY.M.P)"
            echo "Expected format: year.major.patch (e.g., 2025.1.5)"
            exit 1
          fi

      - name: Promote to production
        uses: DoYouHost/workflows/.github/workflows/promote-r2.yml@main
        with:
          version: ${{ inputs.version }}
          directory: serverCollingFanController
          channel: production
          manifest-filename: manifest.json
        secrets: inherit
