name: Promote to Production

on:
  release:
    types: [published, prereleased, created, edited, deleted, released]
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test version to promote (e.g., 2025.1.5)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  debug-event:
    name: Debug Release Event
    runs-on: ubuntu-latest
    steps:
      - name: Debug event information
        run: |
          echo "=== COMPLETE EVENT DEBUG ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Event action: ${{ github.event.action }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "=== RELEASE EVENT DETAILS ==="
            echo "Release tag: ${{ github.event.release.tag_name }}"
            echo "Release name: ${{ github.event.release.name }}"
            echo "Release draft: ${{ github.event.release.draft }}"
            echo "Release prerelease: ${{ github.event.release.prerelease }}"
            echo "Release published_at: ${{ github.event.release.published_at }}"
            echo "Release created_at: ${{ github.event.release.created_at }}"
            echo "Release target_commitish: ${{ github.event.release.target_commitish }}"
          fi
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "=== MANUAL DISPATCH ==="
            echo "Test version: ${{ inputs.test_version }}"
          fi

  check-release:
    name: Check Release
    runs-on: ubuntu-latest
    needs: debug-event
    outputs:
      should-promote: ${{ steps.check.outputs.should-promote }}
      version: ${{ steps.check.outputs.version }}
    steps:

      - name: Check if release should be promoted
        id: check
        run: |
          SHOULD_PROMOTE="false"
          
          # Determine version based on trigger type
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.test_version }}"
            echo "Manual test mode - version: $VERSION"
          else
            VERSION="${{ github.event.release.tag_name }}"
            echo "Release event - version: $VERSION"
          fi
          
          # For manual dispatch, always promote if version is valid
          # For release events, check if it's not draft and not prerelease
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_CONDITIONS_MET="true"
          else
            if [ "${{ github.event.release.draft }}" = "false" ] && [ "${{ github.event.release.prerelease }}" = "false" ]; then
              RELEASE_CONDITIONS_MET="true"
              echo "Release conditions met - promoting to production"
            else
              RELEASE_CONDITIONS_MET="false"
              echo "Skipping promotion - release is draft or prerelease"
            fi
          fi
          
          if [ "$RELEASE_CONDITIONS_MET" = "true" ]; then
            # Check if version follows semantic versioning pattern (YYYY.M.P)
            if [[ "$VERSION" =~ ^[0-9]{4}\.[0-9]+\.[0-9]+$ ]]; then 
              SHOULD_PROMOTE="true"
              echo "✅ Promoting release $VERSION to production"
            else
              echo "❌ Version $VERSION does not follow expected pattern (YYYY.M.P)"
            fi
          fi
          
          echo "should-promote=$SHOULD_PROMOTE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  promote-to-production:
    name: Promote to Production
    needs: check-release
    if: needs.check-release.outputs.should-promote == 'true'
    uses: DoYouHost/workflows/.github/workflows/promote-r2.yml@main
    with:
      version: ${{ needs.check-release.outputs.version }}
      directory: serverCollingFanController
      channel: production
      manifest-filename: manifest.json
    secrets: inherit
