name: Promote to Production

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_version:
        description: 'Test version to promote (e.g., 2025.1.5)'
        required: true
        type: string

permissions:
  contents: read

jobs:
  check-release:
    name: Check Release
    runs-on: ubuntu-latest
    outputs:
      should-promote: ${{ steps.check.outputs.should-promote }}
      version: ${{ steps.check.outputs.version }}
    steps:

      - name: Check if release should be promoted
        id: check
        run: |
          SHOULD_PROMOTE="false"
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.test_version }}"
            echo "=== MANUAL TEST MODE ==="
            echo "Test version: $VERSION"
          else
            VERSION="${{ github.event.release.tag_name }}"
            echo "=== RELEASE EVENT MODE ==="
            echo "Event action: ${{ github.event.action }}"
            echo "Release tag: $VERSION"
            echo "Release draft: ${{ github.event.release.draft }}"
            echo "Release prerelease: ${{ github.event.release.prerelease }}"
            echo "Release published_at: ${{ github.event.release.published_at }}"
          fi
          echo "=================="
          
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            RELEASE_CONDITIONS_MET="true"
            echo "Manual dispatch - skipping release condition checks"
          else
            if [ "${{ github.event.release.draft }}" = "false" ] && [ "${{ github.event.release.prerelease }}" = "false" ]; then
              RELEASE_CONDITIONS_MET="true"
              echo "Release conditions met - not draft and not prerelease"
            else
              RELEASE_CONDITIONS_MET="false"
              echo "Release conditions not met - is draft or prerelease"
            fi
          fi
          
          if [ "$RELEASE_CONDITIONS_MET" = "true" ]; then
            # Check if version follows semantic versioning pattern (YYYY.M.P)
            if [[ "$VERSION" =~ ^[0-9]{4}\.[0-9]+\.[0-9]+$ ]]; then 
              SHOULD_PROMOTE="true"
              echo "✅ Release $VERSION follows semantic versioning and should be promoted to production"
            else
              echo "❌ Version $VERSION does not follow expected semantic versioning pattern (YYYY.M.P)"
              echo "Expected format: year.major.patch (e.g., 2025.1.5)"
            fi
          else
            echo "❌ Release conditions not met, skipping promotion"
          fi
          
          echo "should-promote=$SHOULD_PROMOTE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  promote-to-production:
    name: Promote to Production
    needs: check-release
    if: needs.check-release.outputs.should-promote == 'true'
    uses: DoYouHost/workflows/.github/workflows/promote-r2.yml@main
    with:
      version: ${{ needs.check-release.outputs.version }}
      directory: serverCollingFanController
      channel: production
      manifest-filename: manifest.json
    secrets: inherit
