name: Publish Pages

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'
      - '.github/workflows/publish-pages.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'static/**'
      - '.github/workflows/publish-pages.yaml'
  workflow_dispatch:
  workflow_run:
    workflows: 
      - "Build and Pre-release"
    types:
      - completed

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: mkdir -p output/firmware

      - name: Build
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Fetch firmware files
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: '*'
          out-file-path: output/firmware

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: output
          retention-days: 1

  publish:
    if: github.event_name != 'pull_request'
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5