name: Publish Pages
env:
  SOURCE_FILE: serverCollingFanController.yaml
  PROJECT_NAME: ServerCoolingFanController
  DIR_NAME: serverCollingFanController

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Firmware version to show on the pages (e.g., 2025.1.5)'
        required: false
        type: string
      channel:
        description: 'Channel name (beta/production) to pull firmware from'
        required: false
        default: 'prod'

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - run: mkdir -p output/firmware

      - name: Build
        uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: ./static
          destination: ./output

      - name: Fetch firmware files (specific version)
        if: ${{ github.event.inputs.version != '' && github.event.inputs.version != null }}
        uses: robinraju/release-downloader@v1.12
        with:
          latest: false
          tag: ${{ github.event.inputs.version }}
          fileName: '*'
          out-file-path: output/firmware

      - name: Fetch firmware files (latest by channel)
        if: ${{ github.event.inputs.version == '' || github.event.inputs.version == null }}
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          preRelease: ${{ github.event.inputs.channel == 'beta' }}
          fileName: '*'
          out-file-path: output/firmware

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: output
          retention-days: 1

  publish:
    if: github.event_name != 'pull_request'
    name: Publish
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
